from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

# --- Product Data Models ---
class ProductModel(BaseModel):
    """
    The clean internal data model for the input product (GlowBoost Vitamin C Serum).
    This is the defined output of the Data Ingestion Agent[cite: 63, 64].
    """
    product_name: str = Field(..., description="The marketing name of the product.")
    concentration: str = Field(..., description="The main active ingredient concentration.")
    skin_type: List[str] = Field(..., description="A list of skin types this product is suitable for.")
    key_ingredients: List[str] = Field(..., description="A list of the primary active and beneficial ingredients.")
    benefits: List[str] = Field(..., description="A list of the main effects the product provides.")
    how_to_use: str = Field(..., description="The full instruction string for application.")
    side_effects: str = Field(..., description="Known side effects or cautions.")
    price: str = Field(..., description="The price of the product, including currency.")

class ComparisonProductModel(ProductModel):
    """
    The data model for the fictional comparative product (Product B).
    """
    comparison_name: str = Field(..., description="The fictional name of the comparison product.")
    
# --- Generated Content Models ---

class QuestionAnswer(BaseModel):
    """A single Q&A pair."""
    question: str
    answer: str

class CategorizedQuestion(BaseModel):
    """A single question generated by the agent, categorized."""
    category: str = Field(..., description="Category like Informational, Usage, Safety, etc. [cite: 29]")
    question: str

class ContentLogicModel(BaseModel):
    """
    The model to hold all content generated by the Content Generator Agent[cite: 35].
    """
    user_questions: List[CategorizedQuestion] = Field(
        default_factory=list, 
        description="Minimum of 15 categorized questions for the FAQ page planning. [cite: 28, 29]"
    )
    faq_q_a_pairs: List[QuestionAnswer] = Field(
        default_factory=list, 
        description="The final Q&A pairs used in the FAQ Page (5 Q&As minimum). [cite: 40]"
    )
    product_summary_block: str = Field(
        default="", 
        description="A generated descriptive summary of the product."
    )