# This file holds the structured definitions (Templates) for the final JSON output.

FAQ_PAGE_TEMPLATE = {
    "page_id": "glowboost_faq",
    "page_title": "Frequently Asked Questions",
    "last_updated": "{{current_date}}", # Placeholder for the assembler
    "page_type": "faq",
    "content_blocks": [
        {
            "block_type": "questions_for_planning",
            "description": "Categorized questions generated by AI for future content planning and SEO.",
            "data_source": "ContentLogicModel.user_questions",
            "questions": [] # List of CategorizedQuestion objects
        },
        {
            "block_type": "published_qa_list",
            "description": "The final published Question & Answer pairs (minimum 5 required).",
            "data_source": "ContentLogicModel.faq_q_a_pairs",
            "qa_pairs": [] # List of QuestionAnswer objects
        }
    ]
}

PRODUCT_PAGE_TEMPLATE = {
    "page_id": "glowboost_product_details",
    "product_name": "{{product_data.product_name}}",
    "page_type": "product_details",
    "schema_version": "1.0",
    "sections": [
        {
            "section_title": "Product Overview",
            "content_type": "descriptive_summary",
            "content": "{{content_data.product_summary_block}}" # From Agent 3
        },
        {
            "section_title": "Key Specifications",
            "content_type": "data_points",
            "data_points": [
                {"label": "Concentration", "value": "{{product_data.concentration}}"},
                {"label": "Skin Types", "value": "{{product_data.skin_type_str}}"}, # Will be converted in assembler
                {"label": "Benefits", "value": "{{product_data.benefits_str}}"},
                {"label": "Price", "value": "{{product_data.price}}"},
            ]
        },
        {
            "section_title": "Usage Instructions",
            "content_type": "how_to_use",
            "content": "{{product_data.how_to_use}}"
        }
    ]
}

COMPARISON_PAGE_TEMPLATE = {
    "page_id": "glowboost_vs_competitor",
    "page_title": "GlowBoost vs. The Competition",
    "page_type": "comparison_table",
    "products": [
        "{{product_data.product_name}}",
        "{{product_b_data.comparison_name}}"
    ],
    "comparison_points": [
        {"feature": "Active Ingredient", "glowboost": "{{product_data.key_ingredients[0]}}", "competitor": "{{product_b_data.key_ingredients[0]}}"},
        {"feature": "Target Skin Type", "glowboost": "{{product_data.skin_type_str}}", "competitor": "{{product_b_data.skin_type_str}}"},
        {"feature": "Key Benefit", "glowboost": "{{product_data.benefits[0]}}", "competitor": "{{product_b_data.benefits[0]}}"},
        {"feature": "Price", "glowboost": "{{product_data.price}}", "competitor": "{{product_b_data.price}}"}
    ]
}